on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/checkout@v3
      - run: |
          deno run -A ./main.ts
      - uses: stefanzweifel/git-auto-commit-action@v5
      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./content --project-name=livecdroom --commit-dirty=true
